service: serverless-brando

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'yarn'
    excludeFiles: src/**/*.test.[t|j]s
  


provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, "local"}
  region: eu-west-1
  #profile: deploy-aws
  environment:
    STAGE: ${self:provider.stage}

functions:
  bienvenido:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  buscarPlanetas:
    handler: src/index.detallePlaneta
    events:
      - http:
          path: /buscar/planetas
          method: post
          cors: true
  registrarPersonaje:
    handler: src/index.registrarPersonaje
    events:
      - http:
          path: /registrar/personaje
          method: post
          cors: true
  mostrarPersonaje:
    handler: src/index.mostrarPersonaje
    events:
      - http:
          path: /mostrar/personajes
          method: get
          cors: true